### ISSUE TITLE
missing submodules

### ISSUE THREAD

**Issue by rossduncan** [Quantomatic/pyzx#1]
Several of the example notebooks require `pyzx.examples` which don't actually ship with the public version of the repo.

> AttributeError: module 'pyzx' has no attribute 'examples'

**Comment by akissinger** [comment]
pyzx.examples is now called pyzx.generate. Generally, things in the 'notebooks' folder are being used for our own hacking and testing, so they are often broken or out of date. More stable things will appear in the 'demos' folder as they get written.
