### ISSUE TITLE
CRZ gate decomposition error

### ISSUE THREAD

**Issue by anitalu724** [Quantomatic/pyzx#103]
Hi, according to `pyzx/circuit/gates.py`, your decomposition and tensor of crz(pi/2) is shown below:
![Screen Shot 2022-12-12 at 5 31 48 PM](https://user-images.githubusercontent.com/42861761/207010771-907a6060-3df2-40bb-8dad-bd0805ca0011.png)

However, the correct form of crz(pi/2) should be like this:
![Screen Shot 2022-12-12 at 5 37 20 PM](https://user-images.githubusercontent.com/42861761/207011930-32d17276-d9b0-4741-916d-ce4fb13da729.png)

Refer to this transformation:
![318993810_684855746624910_6597546469576874782_n (1)](https://user-images.githubusercontent.com/42861761/207012131-c19d36e9-e613-4ebd-9561-c5d967261861.png)

May I submit a PR to modify this bug?

**Comment by jvdwetering** [comment]
So a problem here is that different libraries and people use different standards for this gate. I believe I based the current definition on the qasm spec, but I can check

**Comment by jvdwetering** [comment]
Yes QASM3.0 seems to use your definition. Which is annoying because now the specs aren't compatible apparently?
I don't really know how to deal with this now.

**Comment by dlyongemallo** [comment]
PR #156 specifically adds a test to document the behaviour of `rz` and `crz`. I think this issue can be closed.

**Comment by dlyongemallo** [comment]
This issue can be closed.
