### ISSUE TITLE
qasmparser.py raises Invalid specification error when trying to import a phase of "-pi"

### ISSUE THREAD

**Issue by bastibock** [Quantomatic/pyzx#112]
What I'm trying to do:
- Create a PyZX cricuit from a qasm file

Bug:
- When having a gate with a phase of -pi, e.g. `rx(-pi) qb_0[0];` , the qasm import raises a type error: `TypeError: Invalid specification -`

Bugfix:
- add this specific case with another elif statement on line 312 in qasmparser.py: 
`elif val == '-':
     phase = -1`
- Probably not the most elegant way, but it works for me locally.
- I can also submit a PR with the proposed bugfix, if wished.

**Comment by jvdwetering** [comment]
Thanks for the report!
