### ISSUE TITLE
`pyzx.draw` not displaying in shell mode

### ISSUE THREAD

**Issue by JosephDenman** [Quantomatic/pyzx#113]
I'm executing the following program in a shell context.

```
import pyzx as zx
import numpy as np
import matplotlib.pyplot as plt

num_qubits = 15
depth = 15
circuit = zx.generate.cliffordT(num_qubits, depth)
zx.draw(circuit)
plt.show()

x_axis = np.array([2, 8])
plt.plot(x_axis)
plt.show()
```

The second plot displays in a window, but the first plot does not. I tried executing on a Mac M2 with Python version `3.11.2` and `matplotlib` version `3.7.0` with the latest version of `pyzx`. I also tried running it on a different Intel Mac with Python version `3.9.16` and `matplotlib` version `3.7.0`. The behavior is the same on both devices.

**Comment by akissinger** [comment]
By default, PyZX uses a javascript drawing backend, which doesn't work in shell mode. It might work if you set the backend to matplotlib after importing pyzx:

    zx.settings.drawing_backend = 'matplotlib'

**Comment by jvdwetering** [comment]
I think this might be relevant for you: https://stackoverflow.com/questions/42430260/is-it-possible-to-show-multiple-plots-in-separate-windows-using-matplotlib
This is just the way matplotlib works I think.

**Comment by JosephDenman** [comment]
I see. Thanks!
