### ISSUE TITLE
Support for OpenQASM 3.0

### ISSUE THREAD

**Issue by fvirdia** [Quantomatic/pyzx#116]
Hi there,

I am trying to use PyZX to attempt reducing the footprint of some circuits I designed in Qiskit.
When trying to run `pyzx.qasm` on the QASM source generated by Qiskit, I was getting an error on `import 'stdgates.inc'`, which I understand is a library of "standard" gates used by Qiskit.

I tried replacing the line with the content of [stdgates.inc](https://github.com/openqasm/openqasm/blob/main/examples/stdgates.inc), however this results in `TypeError: Arguments for custom gates are currently not supported: p(λ) a { ctrl @ gphase(λ) a; }` on the very first "phase" gate in the file. 

I could try downgrading to a previous Qiskit, however I was wondering if there is any way to support this out of the box, since anyway it seems OpenQASM 2.0 is considered deprecated.

**Comment by dlyongemallo** [comment]
Hi, @fvirdia,

Is there anything else you need? PR #151 was just merged which adds support for the OpenQASM 3 header format and the `p` gate.

**Comment by dlyongemallo** [comment]
PR #156 adds supports for OpenQASM 3 format. I tried some exports from qiskit and they seem to import just fine, so unless there are requests for additional qasm gates not covered by that PR, this issue can be closed.

**Comment by dlyongemallo** [comment]
I think this issue can be closed now.
