### ISSUE TITLE
hsimplify has no attribute 'to_hbox'

### ISSUE THREAD

**Issue by WhiteSymmetry** [Quantomatic/pyzx#117]
h = g.copy()
zx.simplify.spider_simp(h, quiet=True)
zx.hsimplify.to_hbox(h)
m = zx.hrules.match_hpivot(h)
print(m)
display(zx.draw(h,labels=True))
zx.hrules.hpivot(h,m)
display(zx.draw(h,labels=True))

AttributeError: module 'pyzx.hsimplify' has no attribute 'to_hbox'
https://github.com/Quantomatic/pyzx/blob/master/demos/hyperpivot.ipynb

**Comment by jvdwetering** [comment]
Hmm, looks like this function got renamed at some point. `to_hbox()` is now called `to_hypergraph_form()`.

**Comment by WhiteSymmetry** [comment]
Thanks. Okey.
