### ISSUE TITLE
A recent update is not part of the standard installing.

### ISSUE THREAD

**Issue by danielecuomo** [Quantomatic/pyzx#120]
As it has been recently introduced the call to `to_clifford_normal_form_graph(g)`
(Thanks a lot for that!)

I just run (4-July-2023) the command `pip install pyzx`.   

However, the new function seems not to be part of the `pyzx.simplify` package.

Error on screen: `module 'pyzx.simplify' has no attribute 'to_clifford_normal_form_graph'`

**Comment by jvdwetering** [comment]
That's because I have not yet pushed a new version of PyZX to pip (I should do this sooner rather than later I think), so it is not available yet. You can get the latest source release by doing `pip install git+https://github.com/Quantomatic/pyzx.git`.

**Comment by danielecuomo** [comment]
<img width="778" alt="Screenshot 2023-07-04 at 20 22 44" src="https://github.com/Quantomatic/pyzx/assets/37900917/e0b7a171-3f50-4332-8a5c-1147a990d853">

Amazing!

**Comment by dlyongemallo** [comment]
The [https://github.com/Quantomatic/pyzx/releases/tag/v0.8.0](v0.8.0) release includes `to_clifford_normal_form_graph`. This issue can be closed.
