### ISSUE TITLE
Graph qubit_count method returns a floating point number

### ISSUE THREAD

**Issue by RazinShaikh** [Quantomatic/pyzx#133]
The `qubit_count` method in graph_s.py is implement as the following where its output is based on the max value of qubit information stored in the `_qindex` dictionary. 
```python
def qubit_count(self):
    if self._qindex: self._maxq = max(self._qindex.values())
    else: self._maxq = -1
    return self._maxq + 1
```
Since `qubit` is same as the y coordinate of a node, it is not always an integer. This makes the above method return a floating point number which breaks methods like `extract_circuit`.

**Comment by jvdwetering** [comment]
I don't believe extract_circuit uses any positioning information, only the g.inputs() and g.outputs() information. The reason this function returns the maximum value is so that you can get the 'height' of the diagram. That's maybe not intuitive, but changing this would require possibly other changes in the drawing code that check for the size of the diagram.

**Comment by RazinShaikh** [comment]
I get the error on line 510 in the `clean_frontier` method that's called by `extract_circuit` on line 636. The error is due to `qubit_count` returning a floating point.

**Comment by RazinShaikh** [comment]
You can probably reproduce it by clicking `extract_circuit` in the simplify menu for a diagram that has been dragged around with the mouse.

**Comment by jvdwetering** [comment]
Ah right, that function was implemented by someone else, who probably didn't know about this special behaviour.
That function really should be using len(outputs) instead, that's what the other functions use.

**Comment by RazinShaikh** [comment]
Now it fails at line 98 in graphparser.py
```python
    for i in range(c.qubits):
```
when trying to convert the extracted circuit back to graph

**Comment by jvdwetering** [comment]
What error does it give there? `c` should be a Circuit, not a graph, so I don't see how this same bug could apply.

**Comment by RazinShaikh** [comment]
I get the following error.
```
Traceback (most recent call last):
  File "C:\Users\Razin Shaikh\OneDrive\Documents\code\zxlive\zxlive\mainwindow.py", line 356, in reduce
    new_graph = reduction["function"](new_graph)
  File "C:\Users\Razin Shaikh\OneDrive\Documents\code\zxlive\zxlive\mainwindow.py", line 392, in <lambda>
    'extract_circuit': {"text": "extract_circuit", "tool_tip":"extract_circuit", "function": lambda g: extract_circuit(g).to_graph(), "in_place": False},
  File "C:\Users\Razin Shaikh\OneDrive\Documents\code\zxlive\../pyzx\pyzx\circuit\__init__.py", line 268, in to_graph
    return circuit_to_graph(self if zh else self.to_basic_gates(),
  File "C:\Users\Razin Shaikh\OneDrive\Documents\code\zxlive\../pyzx\pyzx\circuit\graphparser.py", line 98, in circuit_to_graph
    for i in range(c.qubits):
TypeError: 'float' object cannot be interpreted as an integer
```
This is circuit I used:
![image](https://github.com/Quantomatic/pyzx/assets/28257517/2f5c26fd-3606-46ed-8c4c-936cb2d1f2ed)

**Comment by jvdwetering** [comment]
Does that fix it?

**Comment by jvdwetering** [comment]
Okay, another try.

**Comment by RazinShaikh** [comment]
It seems to work now 👍
