### ISSUE TITLE
behaviour of `qasmparser` is unclear when `parse` is called multiple times

### ISSUE THREAD

**Issue by dlyongemallo** [Quantomatic/pyzx#148]
It's unclear how to use `qasmparser` if there are multiple strings or circuits to be parsed. In particular, `parse` has behaviour which is surprising to me. I expect each call to basically be independent and return a circuit based on the input string. What actually happens is `parse` builds on top of the circuit processed in previous calls.

In particular, it looks to me like [this line](https://github.com/Quantomatic/pyzx/blob/master/pyzx/circuit/qasmparser.py#L65) is intended to clear the previous state, but is bugged because `gates` rather than `self.gates` is used. 

Repro case:
```
from pyzx.circuit.qasmparser import QASMParser
s = """
OPENQASM 2;
include "qelib1.inc";
qreg q[1];
h q[0];
"""
p = QASMParser()
c1 = p.parse(s)
c2 = p.parse(s)
print(c1)
print(c1.gates)
print(c2)
print(c2.gates)
```

Expected output:
```
Circuit(1 qubits, 0 bits, 1 gates)
[HAD(0)]
Circuit(1 qubits, 0 bits, 1 gates)
[HAD(0)]
```

Actual output:
```
Circuit(1 qubits, 0 bits, 2 gates)
[HAD(0), HAD(1)]
Circuit(2 qubits, 0 bits, 2 gates)
[HAD(0), HAD(1)]
```

In particular, it is surprising that a subsequent call to `parse` alters the value of `c1`.

**Comment by jvdwetering** [comment]
Yes, I agree that that is weird and unexpected.  I would call that a bug.
