### ISSUE TITLE
`extract_curcuit` can silently corrupt the input graph

### ISSUE THREAD

**Issue by zickgraf** [Quantomatic/pyzx#165]
Consider the following example:
```
import pyzx as zx
g = zx.Graph()
g.add_vertex(zx.VertexType.BOUNDARY, qubit = 0, row = 0)
g.add_vertex(zx.VertexType.Z, qubit = 0, row = 1)
g.add_vertex(zx.VertexType.BOUNDARY, qubit = 0, row = 2)
g.add_edge((0,1))
g.add_edge((1,2), edgetype=zx.EdgeType.HADAMARD)
g.auto_detect_io()
zx.full_reduce(g)

print(g.to_matrix())

circ = zx.extract_circuit(g)

print(g.to_matrix())
```

The output is:
```
[[ 0.70710678+0.j  0.70710678+0.j]
 [ 0.70710678+0.j -0.70710678+0.j]]

[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]
```
Calling `extract_circuit` has silently corrupted the input graph.

PyZX Version: commit https://github.com/Quantomatic/pyzx/commit/e4fe332032f00438440d1e8119b7f337b117d9f8 (current master at the time of writing)

**Comment by jvdwetering** [comment]
Oh that is odd, thanks for reporting. That definitely needs fixing.

**Comment by zickgraf** [comment]
> `extract_circuit` indeed consumes the graph.

I see, thanks for the clarification and the update of the documentation!
