### ISSUE TITLE
pyzx should be aware of polynomial and symbolic phase values

### ISSUE THREAD

**Issue by dlyongemallo** [Quantomatic/pyzx#171]
These features are needed to support zxlive development.

See https://github.com/Quantomatic/zxlive/issues/145 and https://github.com/Quantomatic/zxlive/issues/152 for context.

**Comment by jvdwetering** [comment]
Yes I agree that the logic for dealing with symbolic values should live in PyZX. ZXLive should as much as possible just be a gui front-end.

**Comment by jvdwetering** [comment]
This has been done in b8d5db0. If there are some bugs in this I think we should just make more specific issues.
