### ISSUE TITLE
Composing graphs loses grounds?

### ISSUE THREAD

**Issue by semiclassical** [Quantomatic/pyzx#177]
To represent a one-qubit Z-measurement, I create a green phaseless spider with one input / one output and set it as a ground. At first glance, PyZX can handle this just fine:

```
c=zx.Circuit(1)
c.add_gate("ZPhase",0,phase=0)
g=c.to_graph()
g.set_ground(1)
zx.draw(g)
```

<img width="89" alt="measurement" src="https://github.com/Quantomatic/pyzx/assets/63672881/281c1d1b-d4fe-48ae-89a6-3b9bb38996bd">

However, if I compose this graph with itself (`zx.draw(g*g`) then the second spider is no longer a ground:

<img width="138" alt="measurement2" src="https://github.com/Quantomatic/pyzx/assets/63672881/304b4275-7d9a-4f2e-bf93-e254b57c7f0a">

I've verified this as well for larger examples where the two graphs are different:

```
q=5;

c1=zx.Circuit(q)
for i in range(0,q-1,2):
    c1.add_gate("CNOT",i,i+1)
g1=c1.to_graph()
g1.auto_detect_io()

g2=zx.generate.identity(q)
for i in range(q):
    g2.set_type(2*i+1,1)
    g2.set_ground(2*i+1)
    v = g2.add_vertex(qubit=i,row=2)
    g2.add_edge(g2.edge(v,2*i+1),edgetype=zx.EdgeType.SIMPLE)
g2.auto_detect_io()
```
<img width="522" alt="bad grounds" src="https://github.com/Quantomatic/pyzx/assets/63672881/0da43ce4-d0d4-405b-a4f6-672b6aba08c8">

**Comment by ABorgna** [comment]
Can you try #178 ? That should fix it.
