### ISSUE TITLE
request: applicable rules for given node index

### ISSUE THREAD

**Issue by alexandrupaler** [Quantomatic/pyzx#18]
I found in rules.py a collection of methods for applying simplifications. How difficult would it be to have a method like applicable_rule(node_id) that returns a list of possible rule applications?

**Comment by jvdwetering** [comment]
You mean that you give a specific vertex and it returns all the rules that that vertex can be involved in?
This would be quite tedious to implement as some rules search trough vertices while others search trough edges, and all of them return a match object that is specific to that rule. Nevertheless it wouldn't be very _hard_ per se to implement

**Comment by alexandrupaler** [comment]
Thank you. I was asking because I was thinking of clicking on a node and being presented in a GUI with potential rules that can be applied to that node.

**Comment by jvdwetering** [comment]
So I am currently working on an editor where you can do something similar. Try running the following in a Jupyter notebook:
`e = zx.editor.edit(g) # where g is a graph`
