### ISSUE TITLE
Error in basic_optimization

### ISSUE THREAD

**Issue by vsprasannaa** [Quantomatic/pyzx#196]
Dear All, 

I am new to pyZX, and was trying to do full_reduce followed by basic_optimization: 

```
g = some_circ.to_graph()
zx.full_reduce(g, quiet=False) 
g.normalize()
c_opt = zx.extract_circuit(g.copy(),optimize_czs=True, optimize_cnots=3, up_to_perm=False, quiet=True)
zx.basic_optimization(c_opt, do_swaps=False, quiet=True)
```

Unfortunately, I run into this error in the basic_optimization line: 

`TypeError: Unknown gate SWAP(6,7) `

Can someone please help me with the issue? Thanks in advance! :-)

**Comment by jvdwetering** [comment]
Can you try putting `c_opt.to_basic_gates()` before putting it in `zx.basic_optimization` and see if that works?

**Comment by jvdwetering** [comment]
And you are doing it like this?
`zx.basic_optimization(c_opt.to_basic_gates(), do_swaps=False, quiet=True)`
The function returns a new circuit, it does not change it in place.

**Comment by vsprasannaa** [comment]
Thanks, this works. :-)
