### ISSUE TITLE
Error when running T-count benchmark

### ISSUE THREAD

**Issue by yourball** [Quantomatic/pyzx#20]
Hi,
I'm trying to run benchmarking module in Jupyter notebook /demos/T-count Benchmark.ipynb.
After execution of corresponding line in Jupyter notebook 
`for c in fast_circuits:
    print(c.get_output())`
 I'm getting following error:
 **NameError: name 'ZPhase' is not defined**.

If I comment out the line causing the error 
`c_opt = zx.Circuit.from_graph(g).split_phase_gates().to_basic_gates()
` 
it works on a few circuits and then again throws a new error:
**TypeError: Unknown gate XPhase(0,phase=1)**

Please see screenshots below. Would appreciate any feedback.
Thanks! 

<img width="1110" alt="Screen Shot 2020-01-18 at 3 08 00 PM" src="https://user-images.githubusercontent.com/11663863/72669821-78409500-3a04-11ea-90aa-2b6d381efcb4.png">
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/11663863/72669835-97d7bd80-3a04-11ea-9c44-4425fbfb8ec6.png">
<img width="842" alt="Screen Shot 2020-01-18 at 3 12 35 PM" src="https://user-images.githubusercontent.com/11663863/72669998-331d6280-3a06-11ea-9005-020163701530.png">
<img width="837" alt="image" src="https://user-images.githubusercontent.com/11663863/72670033-97d8bd00-3a06-11ea-8962-4a03b3d751b1.png">
<img width="847" alt="image" src="https://user-images.githubusercontent.com/11663863/72670038-a4f5ac00-3a06-11ea-8505-e9b9a2130fa3.png">

**Comment by jvdwetering** [comment]
Thank you for the report. It should be fixed now
