### ISSUE TITLE
`Graph.to_json` followed by `pyzx.json_to_graph` produces an error

### ISSUE THREAD

**Issue by ABorgna** [Quantomatic/pyzx#203]
This example:
```python
graph = zx.Graph()
graph.add_vertex(zx.VertexType.Z, phase=1)
zx.json_to_graph(graph.to_json())
```
throws an error:
```
File (...)/python3.11/site-packages/pyzx/io.py:84, in json_to_graph(js)
     [82] else: raise TypeError("unsupported type '{}'".format(d['type']))
     [83] if 'value' in d:
---> [84]     g.set_phase(v,_quanto_value_to_phase(d['value']))
     [85] else:
     [86]     g.set_phase(v,Fraction(0,1))

File [(...)/python3.11/site-packages/pyzx/io.py:39], in _quanto_value_to_phase(s)
     [37]     except ValueError:
     [38]         raise ValueError("Invalid phase '{}'".format(s))
---> [39] return Fraction(s)

File (...)/python3.11/fractions.py:115, in Fraction.__new__(cls, numerator, denominator, _normalize)
    [113] m = _RATIONAL_FORMAT.match(numerator)
    [114] if m is None:
--> [115]     raise ValueError('Invalid literal for Fraction: %r' %
    [116]                      numerator)
    [117] numerator = int(m.group('num') or '0')
    [118] denom = m.group('denom')

ValueError: Invalid literal for Fraction: 'π'
```

Weirdly, any other combination of `Graph.to_json`/`graph_to_json` and `Graph.from_json`/`json_to_graph` works correctly.

This is the json from `Graph.to_json()`:
```json
{"wire_vertices": {}, "node_vertices": {"v0": {"annotation": {"coord": [-1, 1]}, "data": {"type": "Z", "value": "\u03c0"}}}, "undir_edges": {}, "variable_types": {}, "scalar": "{\"power2\": 0, \"phase\": \"0\"}"}
```

And this is the one from `json_to_graph`:
```json
{"wire_vertices": {}, "node_vertices": {"v0": {"annotation": {"coord": [-1, 1]}, "data": {"type": "Z", "value": "\\pi"}}}, "undir_edges": {}}
```

The former uses an unicode character to encode π (and also seems to always include the scalar).

- I'm using `pyzx=0.8.0`

**Comment by jvdwetering** [comment]
So what you do seems to be calling the function in io.py instead of the one in graph/jsonparser.py. The io.py one should also be printing a message that it is deprecated (are you seeing this?). I should probably just stop the import of anything from io into the main module, to prevent people from calling this thing.

**Comment by ABorgna** [comment]
Yes, I do get the warning but a deprecated function crashing on a seemingly valid input still seemed a bug to me.
(I found this via a user that was unknowingly mixing both calls on different parts of their program).

Could the method in `io` be replaced with a call to `Graph.from_json`?
Removing the import would also work, although that's a breaking change.
