### ISSUE TITLE
`pyzx.draw()` is incompatible with dark background

### ISSUE THREAD

**Issue by dlyongemallo** [Quantomatic/pyzx#228]
In some environments, it is possible to set use a "dark theme" or "dark mode" in which the background is set to black or a dark colour. The `pyzx.draw()` function assumes that the background is white, and when it is used in such an environment, the edges in the diagram are invisible.

For example, Jupyter lab includes both light and dark themes, and the digrams produced by `pyzx.draw()` are simply impossible to see in the latter:
![2024-05-09_09-34](https://github.com/Quantomatic/pyzx/assets/9248532/2d491ca1-ed73-4639-8f21-dfe588ec958e)
![2024-05-09_09-33](https://github.com/Quantomatic/pyzx/assets/9248532/44c872ca-2499-41f4-a295-0322e62e40c4)

A simple fix would be just to always draw a white background (which is what Qiskit's `QuantumCircuit.draw(output = "mpl")` does. (Of course, if one wants to be fancy, one can provide a way to support multiple colour schemes.)

**Comment by dlyongemallo** [comment]
Oh, wait this seems to already be fixed at HEAD by https://github.com/Quantomatic/pyzx/commit/5a6b2f6ba181dc37c202d71064f5a25b20e3d305.

**Comment by akissinger** [comment]
Yes, I just fixed this to get reasonable looking d3 graphs in vscode.
