### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by EarlMilktea** [Quantomatic/pyzx#232]
I'm now planning to contribute to this repo., but before I proceed, I would like to ask about the coding style.

- Is there any kind of style guideline for this repo?
- If any, is it different from the Python standard (PEP8)?
- Do you have any plans for using formatter like `black` or `ruff format` ?

**Comment by EarlMilktea** [comment]
I see.

Then shall I submit a PR for auto formatting?

**Comment by dlyongemallo** [comment]
Duplicate of issue #122?

**Comment by EarlMilktea** [comment]
@dlyongemallo

Overlooked it. Thank you. I'm totally agree with your opinion.

Let me close this issue to avoid clutter and move to #122 .
