### ISSUE TITLE
Circuit simplification on a predefined circuit topology

### ISSUE THREAD

**Issue by yourball** [Quantomatic/pyzx#25]
Hi PyZX developers!

I have a following question: how to run a circuit optimization (e.g. `zx.simplify.full_reduce(g)`) for a circuit on a predefined hardware topology?

In order to perform the mapping to hardware topology I tried to use a function `map_cnot_circuit`(..) (located In `pyzx.scripts.cnot_mapper`) together with an architecture created using `pyzx.routing.architecture.create_architecture`.
 
I got a very strange result (the output circuit is either empty or only contains a few CNOTs) and a bunch of warning.

Could you guys please help me?

<img width="581" alt="image" src="https://user-images.githubusercontent.com/11663863/73999390-a09c1f00-4932-11ea-8ab5-19a03664dbbb.png">

**Comment by akissinger** [comment]
That function is only intended for circuits containing only CNOT gates. General purpose circuit mapping to architectures is not (yet) supported. It is still an open problem how to do this well within the PyZX simplify-and-extract framework, but we are working on it!

For now, I think the best way to use PyZX for fixed architectures is to run its optimiser before passing the resulting circuit on to a mapping compiler like t|ket>, qiskit, or quilc.
