### ISSUE TITLE
Question about Quipper parser

### ISSUE THREAD

**Issue by khieta** [Quantomatic/pyzx#26]
Hi, I'm wondering what the factor of 2 is for on line 64 of [pyzx/circuit/quipperparser.py](https://github.com/Quantomatic/pyzx/blob/cc34a6ba98ae2be8b825eef4c5714301a1b62a49/pyzx/circuit/quipperparser.py#L64). Is this due to a difference between quipper & PyZX's representation of phase gates? 

For example, I expected the first rotation in [QFT8](https://github.com/Quantomatic/pyzx/blob/master/circuits/QFT_and_Adders/QFT8_before) to be translated as -PI/8, but the produced translation is -PI/4. Am I interpreting the gates wrong? I just want to make sure I'm translating files correctly. Thanks!

**Comment by jvdwetering** [comment]
It's been a while, but if I'm not mistaken this is because Quipper represents a `Z(theta)` rotation as a `diag(theta,-theta)` gate, while a phase gate in the ZX-calculus is `diag(1,theta)`. Hence the conversion factor.

**Comment by jvdwetering** [comment]
Did this answer your question?

**Comment by khieta** [comment]
Yes, thanks!
