### ISSUE TITLE
[Circuit optimisation]: Run pyzx from the command-line without giving destination file. 

### ISSUE THREAD

**Issue by nikoSchoinas** [Quantomatic/pyzx#28]
Hi, 
I tried to run the command _**python -m pyzx opt input_circuit.qasm**_ in order to optimise a circuit but I am getting an error: _**TypeError: expected str, bytes or os.PathLike object, not Namespace.**_

I could post the traceback but in a few words the error is caused by `splitext` method in **_circ2circ.py_** file, line 64:
`base = os.path.splitext(options)[0]`

In python 3.6, `splitext` method uses `os.fspath()` method that takes a string, bytes or os.PathLike object and not a Namespace object (as the error indicates).

`options` is a Namespace object though. 

When I changed the  "base" variable's declaration to `base = "output"`, in order to write the optimised circuit in output.qasm file, everything worked fine.

Another solution is to add the destination file when running the command:  
_**python -m pyzx opt -d output_circuit.qasm input_circuit.qasm**_

Thank you.

**Comment by jvdwetering** [comment]
Thank you for the report. It resulted from a silly mistake, which now should be fixed.
