### ISSUE TITLE
Rows and columns flipped when loading JSON

### ISSUE THREAD

**Issue by rossduncan** [Quantomatic/pyzx#3]
Loading the attached qgraph file gives the rows and columns backwards, so the circuit reports its depth as 2.0.
```
file_name = "small.qgraph"
with open(file_name, 'r') as qgraph :
    js = qgraph.read()
    g3 = zx.json_to_graph(js)
    print(g3.depth())
```

Also, I think the depth should be an integer not a float.

[small.qgraph.zip](https://github.com/Quantomatic/pyzx/files/2305939/small.qgraph.zip)

**Comment by johnie102** [comment]
That the depth is a float is intentional. The depth simply returns the largest 'row' value in the graph, and this can be fractional, as it works as kind of the 'x' value when drawing.
Rows and columns being switched is now fixed.

**Comment by rossduncan** [comment]
Thanks for fixing this John.

I saw from the code that the depth is just the row number.  I am saying that this behaviour is not desirable.  (Also rows and columns should probably be integers too!)

**Comment by johnie102** [comment]
The code actually uses the fact that you can have fractional row numbers in a few places to "insert" new nodes in specific positions without having to reposition every other node. Also quantomatic of course allows floating point values for the coordinates. If we forced row and column numbers to be integers than we would have to either (1) round every coordinate when importing or (2) introduce a new coordinate system specifically for qgraph files.
I agree that it is not very intuitive that these values can be floating points, but for now it is quite useful.
