### ISSUE TITLE
Syntax error compiling `cnot_mapper.py`

### ISSUE THREAD

**Issue by cqc-alec** [Quantomatic/pyzx#30]
```
  *** Error compiling '/tmp/pip-unpacked-wheel-kgj3yp34/pyzx/scripts/cnot_mapper.py'...
    File "/tmp/pip-unpacked-wheel-kgj3yp34/pyzx/scripts/cnot_mapper.py", line 31
      np = pass
              ^
  SyntaxError: invalid syntax
```
Probably should be `np = None` as elsewhere?

**Comment by cqc-alec** [comment]
(By the way this does not prevent successful installation.)

**Comment by jvdwetering** [comment]
Ah well that explains why I didn't catch it. I really need to start writing more unit tests...

**Comment by jvdwetering** [comment]
I also pushed this into a new release, so you can get it via `pip install pyzx --upgrade`
