### ISSUE TITLE
Require Python >= 3.6

### ISSUE THREAD

**Issue by jvdwetering** [Quantomatic/pyzx#32]
So far there is no official minimum Python version that PyZX requires.  I suggest making it Python 3.6 for the following reasons:

I think PyZX is already incompatible with Python 2 so it would be good to make the dropping of that support explicit.

Python 3.4 is already retired, so the earliest release that would make sense is 3.5. However, 3.6 offers more support in terms of typing hints. I'm considering adding these kinds of type hints over the coming period and it would then be useful to have the features of 3.6.

Are there any other considerations I'm missing regarding which version of Python to support?

**Comment by the-legend-of-lia** [comment]
I agree with >= 3.6

**Comment by jvdwetering** [comment]
So I was just made aware that pyzx currently does not work in 3.6 because the line
```class BaseGraph(Generic[VT, ET], metaclass=DocstringMeta):```
in `pyzx.graph.base.py` gives the exception `TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases`.
This is an issue with subclassing from the typing module that has been fixed in 3.7. I know no other way around this.

**Comment by ABorgna** [comment]
There could be a short CI workflow in Github Actions to run the unit tests in all supported versions. (Actions is free for public repositories). There is a model for python packages.

I can make the PR if you are OK with it.

**Comment by jvdwetering** [comment]
I've been thinking of setting up CI for a while now, but I'm not sure how to do it. I've also been working on integrating type hinting, so setting up CI with mypy would be a good idea as well

**Comment by jvdwetering** [comment]
PyZX now requires Python3.6
