### ISSUE TITLE
Submitting to JOSS?

### ISSUE THREAD

**Issue by wetneb** [Quantomatic/pyzx#38]
I was wondering if you had considered submitting pyzx to the [Journal of Open Source Software](https://joss.theoj.org/)?

Pyzx strikes me as a mature software project and it would be good to recognize it at such, not just for your own benefit but also to encourage good open source development practices in the ACT community.

You already have an accompanying paper for the tool, so there would not be much to write up.

**Comment by jvdwetering** [comment]
Aleks and I had in fact considered that option, but ended up sending our the paper you mentioned to the proceedings of QPL: http://eptcs.web.cse.unsw.edu.au/paper.cgi?QPL2019.14
Do you know whether the Journal of Open Source Software would look kindly on work that has already been accepted elsewhere?

**Comment by wetneb** [comment]
Yes dual submissions seem to be totally in the spirit of JOSS, they even strike partnerships to do that systematically: https://blog.joss.theoj.org/2018/12/a-new-collaboration-with-aas-publishing
I expect QPL reviewers and JOSS reviewers to be looking for different things.

That being said you already have a DOI via QPL, so perhaps you don't want to duplicate that…

**Comment by jvdwetering** [comment]
I have read up a bit on JOSS. It seems it is meant more to replace the existence of dedicated software papers. But seeing as we already spent the effort in making such a paper, I don't see much value in also pursuing a JOSS paper.
