### ISSUE TITLE
Split extract.py into submodules

### ISSUE THREAD

**Issue by ABorgna** [Quantomatic/pyzx#39]
The extract module contains multiple independent extraction functions (`streaming_extract`, `modified_extract`, `clifford_extract`, `simple_extract`, `circuit_extract`), including some that are commented-out.
We could split them into `extract.*` submodules, so it's easier to modify or add new extraction strategies.

I can make the PR if this is OK.

**Comment by jvdwetering** [comment]
You're right that that file is an absolute mess right now. I was already planning to clean it up, so leave it as it is for now.

**Comment by jvdwetering** [comment]
Cleaned up the file significantly in commits caa3740cf19ea5224ce7d606d0d852280cb72e89 97b2f4b2fa0ebe060b2f87a487512c0a71eefab5
