### ISSUE TITLE
CNOT_HAD_PHASE_circuit() argument differences

### ISSUE THREAD

**Issue by johnzl-777** [Quantomatic/pyzx#42]
I wanted to give the "Getting Started" example in the documentation a try but I ran into the following problem:

```python
TypeError: CNOT_HAD_PHASE_circuit() got an unexpected keyword argument 'depth'
```

Invoking `CNOT_HAD_PHASE_circuit()` without any arguments (just to tease what the arguments should be) gives the following:

```python
TypeError: CNOT_HAD_PHASE_circuit() missing 4 required positional arguments: 'qubits', 'gates', 'p_had', and 'p_t'
```

Which is rather odd considering the PyZX source gives the following, expected definition:

```python
def CNOT_HAD_PHASE_circuit(
        qubits: int, 
        depth: int, 
        p_had: float = 0.2, 
        p_t: float = 0.2, 
        clifford:bool=False
        ) -> Circuit:
```

The `gates` keyword argument seems to come from nowhere and I'm not sure if this is part of a larger problem or something with my installation.

I'm currently running Python 3.7.3 with PyZX installed through the recommended `pip install pyzx` in a Docker environment. I've also done the same installation locally on my Mac OS (just to make sure my Docker image wasn't the culprit.

**Comment by johnzl-777** [comment]
I went ahead and used `inspect.getsource()` to get a better look at the definition from the `pip install` and I get the following:

```python
def CNOT_HAD_PHASE_circuit(qubits, gates, p_had, p_t, clifford=False):
    """Returns a Circuit consisting of CNOT, HAD and phase gates. 
    The default phase gate is the T gate, but if ``clifford=True``, then
    this is replaced by the S gate."""
```

**Comment by jvdwetering** [comment]
The 'Getting started' in the documentation is based on the latest github version wherein `p_had` and `p_t` are optional arguments. I forgot I hadn't pushed this yet to the PyPI version.
I'm overdue for pushing a new version to PyPI anyway, so this should be fixed soon.

**Comment by johnzl-777** [comment]
Awesome! Is there a possible ETA on the new version being pushed? 

And I guess I'll default to the "git clone and install" method for the time being 😄

**Comment by jvdwetering** [comment]
Maybe next week? But then again, maybe not. "Soon"

**Comment by jvdwetering** [comment]
Version 0.6.0 was just pushed to PyPI, so the pip version and the documentation should match up.
