### ISSUE TITLE
`AllFeatures.ipynb` text mismatch

### ISSUE THREAD

**Issue by alexcowtan** [Quantomatic/pyzx#43]
If I run `pip install pyzx` followed by running the notebook, I receive various errors, presumably because the pip version is out of sync with the source, as per https://github.com/Quantomatic/pyzx/issues/42.

When I install from source and run the notebook, there are a few sections where the text doesn't accurately describe what's going on.

1. Text under cell 20 says: "This method combines all T-like phases with a phaseless spider to turn it into a phase gadget." However, it looks like there are still 5 spiders that haven't been gadgetized.
2. Text under cell 21 says: "That has reduced the T-count from 22 down to 18!" except when I run the cell, the T-count is 8.
3. Text under cell 22 says: "We do one final round of clifford_simp to make the graph a bit smaller." except it doesn't actually make it any smaller.
4. In "Extracting and Optimizing Circuits" it says: "For extracting circuits out of ZX-graphs there is only a single method in PyZX that you have to call: `zx.extract.streaming_extract`", but we never actually call that method.

**Comment by alexcowtan** [comment]
I should say that I would fix these myself, except:

- I don't know how much you will want to change for the next release anyway.
- I'm not sure what to replace cells 20-22 with.

**Comment by jvdwetering** [comment]
Good find. I'll take a look.

**Comment by jvdwetering** [comment]
The pip version is now pushed to 0.6.0, so the inconsistencies should be fixed now.
