### ISSUE TITLE
qc_name, qasm_name

### ISSUE THREAD

**Issue by RitaAhmadi** [Quantomatic/pyzx#44]
Hi, Why do some gates not have qc_name like "ZPhase" and "XPhase" and some like SWAP, CX are given "undefined" as names in those fields? I think swap is swap in qasm.

**Comment by jvdwetering** [comment]
I recently changed how this naming works, so it might be I made some errors there.
But if I'm not mistaken, since the baseclass Gate defines `qc_name="undefined"`, ZPhase and XPhase inherit it from there, while SWAP and CX inherit from CNOT that redefines `qc_name`, hence why they need to explicitly state that the name is undefined.

**Comment by MobiusFatimah** [comment]
@jvdwetering I checked it again, and all is as you said. Now for SWAP in .qc description, it prints "Z" and ZPhase and XPhase raise errors. But if I am correct, .qc means latex code, then why ZPhase and XPhase do not have latex names?

**Comment by jvdwetering** [comment]
I basically only filled in the names for the gates for which I knew the correct .qc name. If you have a source for what I should make the names of the other gates, then I'm happy to add them as well.

**Comment by mhibti** [comment]
Dear all,
I have some problems with gates following a conversion from qiskit to qasm. 
Here is the begining of the file (the whole can be provided if needed).
Do I mess something or this is just some missing gates.
Thanks
`OPENQASM 2.0;
include "qelib1.inc";
qreg q0[15];
creg c0[1];
ry(1.5707963267948968) q0[0];
ry(0.9272952180016122) q0[1];`

**Comment by mhibti** [comment]
TypeError: Unknown gate name: ry(1.5707963267948968) q0[0]

**Comment by mhibti** [comment]
I will do ! Thanks

**Comment by jvdwetering** [comment]
I'll close this since the original issue was solved, and I've made a new issue for the implementation of the ry gate in #90
