### ISSUE TITLE
Mixed British and American spelling

### ISSUE THREAD

**Issue by MobiusFatimah** [Quantomatic/pyzx#45]
Hi, the mixed spelling of functions makes it hard to remember, for instance, **normalise()**, but **optimize()**. In the document also, **optimization** has spelled in both ways, so search does not find all matches.

**Comment by jvdwetering** [comment]
Yeah that is a good point. I'll discuss with Aleks what we should do about this

**Comment by akissinger** [comment]
Initially, it was my intention to use US spellings everywhere, as this is sortof an unwritten rule for international coding standards, but I haven't been following that very well. Shall we make that a written rule?

**Comment by jvdwetering** [comment]
Yeah let's do that

**Comment by jvdwetering** [comment]
I've just pushed a commit that takes care of at least 4 functions that had british spelling, i.e. any that had one of the following words in it: normalise, optimise, colour, neighbour.
I think this covers most of the Britishness, but if there is anything else, let me know.
228137c3db8d768894bbdaadc7d2bc48f1d025f5

**Comment by jvdwetering** [comment]
I think this is fully resolved now.
