### ISSUE TITLE
verify_equality checks equality up to a permutation

### ISSUE THREAD

**Issue by tangyaocn** [Quantomatic/pyzx#47]
It appears that the `Circuit.verify_equality` method checks equality up to a permutation rather than strict equality. I tested it with several different circuits with the final permutation changed. The method would still return true. I think this is a useful feature because I don't have to revert the final permutation in order to test whether a circuit optimization strategy works. However, it should be mentioned in the API documentation.

**Comment by jvdwetering** [comment]
Good catch. I agree it is a useful feature to have though. I'll make it an argument you can set in the function
