### ISSUE TITLE
Faulty ZH rewites in the editor and perhaps beyond

### ISSUE THREAD

**Issue by RDPEast** [Quantomatic/pyzx#49]
The following can occur:
![image](https://user-images.githubusercontent.com/13621329/87878821-06fb9200-c9e7-11ea-9b2e-e69e528d3673.png)
and with multiple elements selected

![image](https://user-images.githubusercontent.com/13621329/87878833-12e75400-c9e7-11ea-8748-8d52537ddf3a.png)

**Comment by jvdwetering** [comment]
These bugs should now be fixed, so I'm closing the issue for now. But if you find new bugs in the rewriting system of the editor feel free to reopen.
