### ISSUE TITLE
ctrl-click and ctrl-drag on macOS

### ISSUE THREAD

**Issue by aggrushin** [Quantomatic/pyzx#53]
Hello! First of all, very nice package! 
One issue I found on Mac OS is ctrl+click on a Mac is mapped to a right mouse click. 
In the editor mode this results in boxes appearing when defining vertices and unconnected edges, that don't attach to vertices, see attached snapshots. Any idea of what is the problem here?  I tried several browsers but still same problem :/ Thanks!

<img width="1164" alt="Screen Shot 2020-09-06 at 12 42 34 PM" src="https://user-images.githubusercontent.com/10845053/92324096-b8f62880-f03e-11ea-8e94-e9717ecc8957.png">

<img width="1163" alt="Screen Shot 2020-09-06 at 12 43 03 PM" src="https://user-images.githubusercontent.com/10845053/92324095-b85d9200-f03e-11ea-83a2-b60c90540842.png">

<img width="1143" alt="Screen Shot 2020-09-06 at 12 43 13 PM" src="https://user-images.githubusercontent.com/10845053/92324093-b72c6500-f03e-11ea-8a00-c09ec61c5ff5.png">

**Comment by aggrushin** [comment]
A workaround that seems to work for me is to replace ctrlKey for altKey in the file zx_editor_widget.js

**Comment by jvdwetering** [comment]
I don't have a mac so I can't test for myself, can you see if the following fix works.
Lines 81-85 of zx_editor_widget.js are
`.on("keydown.brush", function() {shiftKey = d3.event.shiftKey || d3.event.metaKey;
            								 ctrlKey  = d3.event.ctrlKey;})
            .on("keyup.brush", function() {shiftKey = d3.event.shiftKey || d3.event.metaKey;
            							   ctrlKey  = d3.event.ctrlKey;})`

Change this to:
`.on("keydown.brush", function() {shiftKey = d3.event.shiftKey;
            								 ctrlKey  = d3.event.ctrlKey || d3.event.metaKey;})
            .on("keyup.brush", function() {shiftKey = d3.event.shiftKey;
            							   ctrlKey  = d3.event.ctrlKey || d3.event.metaKey;})`
(i.e. make metaKey a synonym for ctrl)
Then you should be able to use Command+Click on Mac to do the thing that requires ctrl+click on Windows.

**Comment by jvdwetering** [comment]
Hmm, although looking at other parts of the code in that file, it seems that I would have to restructure it to actually use those local variables shiftKey and ctrlKey, instead of relying on the d3.event.ctrlKey thing.

**Comment by aggrushin** [comment]
> I don't have a mac so I can't test for myself, can you see if the following fix works.
> Lines 81-85 of zx_editor_widget.js are
> `.on("keydown.brush", function() {shiftKey = d3.event.shiftKey || d3.event.metaKey; ctrlKey = d3.event.ctrlKey;}) .on("keyup.brush", function() {shiftKey = d3.event.shiftKey || d3.event.metaKey; ctrlKey = d3.event.ctrlKey;})`
> 
> Change this to:
> `.on("keydown.brush", function() {shiftKey = d3.event.shiftKey; ctrlKey = d3.event.ctrlKey || d3.event.metaKey;}) .on("keyup.brush", function() {shiftKey = d3.event.shiftKey; ctrlKey = d3.event.ctrlKey || d3.event.metaKey;})`
> (i.e. make metaKey a synonym for ctrl)
> Then you should be able to use Command+Click on Mac to do the thing that requires ctrl+click on Windows.

Unfortunately, this didn't seem to work for me, but I did try again what I suggested but this time replacing all ctrlKey with metaKey and it worked now with Command+click, as one would expect. But maybe this is not ideal in other parts of the code.

**Comment by jvdwetering** [comment]
Great! I can work with that. I can just make all ctrlKey a ctrlKey || metaKey (and update the docs).

**Comment by aggrushin** [comment]
Great thanks! A tangentially related observation: In the iPad (which I sometimes use to code quick stuff) is kind of hard to press a key and click at the same time. I checked and the widget ctrl+click works with a trackpad, but not when you press ctrl and touch on the screen (which should in principle be equivalent to a ctrl-click in general). Not sure if there is a quick solution for this.

**Comment by jvdwetering** [comment]
So it looks like javascript makes a difference between 'click' events and 'touch' events that might be causing this behaviour.
https://stackoverflow.com/questions/11397028/document-click-function-for-touch-device
But it also says that most browsers should fire a click event when you touch the screen.

**Comment by aggrushin** [comment]
I see. I am using an app called [Juno Connect](https://juno.sh/junoconnect/) to run a notebook on a remote server, so it is not precisely a browser.
Perhaps if I try to forward it to the browser it might work. It would be nice to get the app compatibility though! but I understand maybe not a priority.

**Comment by aggrushin** [comment]
I also tried to run pyzx in the [Juno](https://juno.sh) app (different from Juno Connect) which allows a local version of a code to run, but I couldn't get the package to import

![IMG_02CB38DC0F6F-1](https://user-images.githubusercontent.com/10845053/92329238-88c28000-f066-11ea-8009-013c97000d7e.jpeg)
![IMG_1423](https://user-images.githubusercontent.com/10845053/92329237-852ef900-f066-11ea-9ff2-e6b56be80af7.PNG)

**Comment by jvdwetering** [comment]
Hmm, the error originates from a call in typing.py, which makes me think that Juno is perhaps expecting an older version of python or doesn't have fully compatibility with mypy?

**Comment by aggrushin** [comment]
I just installed mypy 0.782, which runs on Juno (I can import the package).
Juno runs on Python 3.6.6 so maybe there is some incompatibility?

**Comment by aggrushin** [comment]
Although Juno only works with pure python packages though (at least this is what they [say](https://juno.sh/faq/) ), could this be an issue?

**Comment by jvdwetering** [comment]
I've just pushed a commit that should allow you to use command-click in the editor. Can you test whether it works for you?

**Comment by aggrushin** [comment]
Indeed it works. I wasn't updated downloading from the pip (not sure how is pip updates upon new commits), but when I added the file it worked :) Thanks!

**Comment by jvdwetering** [comment]
Yeah for pip I have to make a separate release for which I want to bunch up a bit more stuff than just pushing a single commit at once.
