### ISSUE TITLE
Cannot simply CNOTs to SWAP with basic_optimization

### ISSUE THREAD

**Issue by Thenerdstation** [Quantomatic/pyzx#65]
I'm trying to do a simple circuit optimization (optimizing 3 CNOTs into a single SWAP), but it's not optimizing it correctly.
Version: 0.6.4

Example code from my terminal.
```python
c = pyzx.Circuit(2)
c.add_gate("CNOT", control=0, target=1)
c.add_gate("CNOT", control=1, target=0)
c.add_gate("CNOT", control=0, target=1)
d = pyzx.basic_optimization(c, do_swaps=True)
print(d)  # Circuit(2 qubits, 3 gates)
```

The circuit has 3 gates, but should be optimized to only have 1. What am I doing wrong here?

**Comment by jvdwetering** [comment]
For technical reasons the `basic_optimization` function calls `to_basic_gates()` on things like SWAPs produced by the simplification, so while the simplification does see that there is a SWAP here, it is automatically expanded into three CNOTs.
If you don't want this, then there are two things you could do. 
Either postprocess your result, looking for triples of CNOTs, and replace these by SWAPs (this will catch all of them, as this is how the output circuit of a `basic_optimization` call is structured), or else delve into the nitty gritty in the `optimize.py` file, build an `Optimizer` instance, and call `parse_forward` to get the actual SWAPs (and Pauli's) that are pushed towards the end of the circuit (look at how the `parse_circuit` method is structured).
I recommend you go the first route.

**Comment by Thenerdstation** [comment]
Why do you automatically expand SWAP gates? That seems counter productive to a circuit optimizer.

**Comment by jvdwetering** [comment]
Apologies, I had forgotten that I had already implemented a more straightforward way to do this:
```
c = pyzx.Circuit(2)
c.add_gate("CNOT", control=0, target=1)
c.add_gate("CNOT", control=1, target=0)
c.add_gate("CNOT", control=0, target=1)
o = pyzx.optimize.Optimizer(c)
d, corr = o.parse_circuit(do_swaps=True,separate_correction=True)
print(d)
print(corr)
```
