### ISSUE TITLE
Error synthesising with `steiner_gauss` (2)

### ISSUE THREAD

**Issue by alexcowtan** [Quantomatic/pyzx#71]
OK, this one I think is a bug. I am running Python 3.9.5, and am running pyzx from the master branch.

Given the following code:
```
import pyzx as zx
from pyzx.routing.architecture import Architecture, Graph
from pyzx.routing.steiner import steiner_gauss
from pyzx.routing.parity_maps import CNOT_tracker

mat = zx.Mat2.id(4)
mat.row_add(1, 0)
mat.row_add(2, 0)
mat.row_add(3, 0)
mat.row_add(0, 1)
mat.row_add(1, 2)
mat.row_add(2, 3)
print(mat)

connections = [(0, 1), (0, 2), (0, 3)]
graph = Graph(None)
vertices = graph.add_vertices(4)
graph.add_edges(connections)
print(graph)
arch = Architecture(name="attempt", coupling_graph=graph)
c = CNOT_tracker(4)
print("Perform Steiner Gauss:\n")
steiner_gauss(mat, arch, True, y = c)
```

I get the following error:

```
Traceback (most recent call last):
  File "/Users/aletan/pyzx/pyzx_attempt.py", line 23, in <module>
    steiner_gauss(mat, arch, True, y = c)
  File "/Users/aletan/pyzx/pyzx/routing/steiner.py", line 106, in steiner_gauss
    steiner_reduce(pivot, current_row, nodes, True)
  File "/Users/aletan/pyzx/pyzx/routing/steiner.py", line 46, in steiner_reduce
    next_check = next(steiner_tree)
  File "/Users/aletan/pyzx/pyzx/routing/architecture.py", line 160, in steiner_tree
    best_option = min(options, key=lambda x: x[2])
ValueError: min() arg is an empty sequence
```

This should be a valid input matrix, as it corresponds to the CNOT circuit with CNOTs where the row additions are, and I believe I have constructed the Graph, Architecture etc correctly.

**Comment by jvdwetering** [comment]
@Aerylia Do you know what is going on?

**Comment by Aerylia** [comment]
Yeah, the code is functional, but the Steiner-gauss implemented in pyzx is supported for architectures with a Hamiltonian path. The given architecture does not have one.

**Comment by alexcowtan** [comment]
Ah, so the recursive version of the algorithm described in https://arxiv.org/pdf/1904.00633.pdf does not have an implementation?

**Comment by Aerylia** [comment]
Not on this repo, I never made a PR and now I don't have the access anymore 😅

**Comment by cqc-melf** [comment]
Does it have an implementation somewhere else?

**Comment by alexcowtan** [comment]
@cqc-melf we have a fork in CQCL.

**Comment by Aerylia** [comment]
Yes, I was just typing. The recursive version is called rec_steiner_gauss

**Comment by cqc-melf** [comment]
Perfect, I will take a look. Thank you!

**Comment by Aerylia** [comment]
If you have questions, just drop me an email: ariannemeijer@gmail.com
I will close the issue.
