### ISSUE TITLE
Is `full_optimize` supposed to be nondeterministic?

### ISSUE THREAD

**Issue by khieta** [Quantomatic/pyzx#85]
Hi, I'm working on gathering benchmark data for different quantum circuit optimizers. I'm running PyZX's optimizations using the script [here](https://github.com/inQWIRE/VOQC-benchmarks/blob/main/run_pyzx.py), which calls both `full_reduce` and `full_optimize`.

I noticed that `full_optimize` produces different outputs on different runs. For example, on [this input circuit](https://github.com/inQWIRE/VOQC-benchmarks/blob/main/staq-benchmarks/gf2%5E4_mult.qasm) I got the following gate counts over a series of 5 runs:
```
Total 310, T 54, 2-qubit 239
Total 345, T 58, 2-qubit 266
Total 344, T 58, 2-qubit 266
Total 311, T 55, 2-qubit 236
Total 356, T 59, 2-qubit 278
```
I just wanted to confirm that this is the expected behavior. 

In the [documentation](https://pyzx.readthedocs.io/en/latest/api.html) you have a note that says that `phase_block_optimize` (used by `full_optimize`) "will give wrong output when fed smaller rotation gates, or Toffoli-like gates" -- what does this mean? I want to make sure that I'm not passing `full_optimize` invalid inputs.

Also, please let me know if you see any other problems with my script for running PyZX.

Thanks!

**Comment by jvdwetering** [comment]
`full_optimize` uses the TODD routine, which is indeed not deterministic. This is deliberate as it makes is possible to find better results by running the algorithm several times. If you are willing to do some manual digging to make it deterministic, in the `todd_iter` function in `pyzx/todd.py` there is call to `random.shuffle`. If you remove this it should become deterministic.

**Comment by khieta** [comment]
Thanks!
