### ISSUE TITLE
getting started example in demo notebook vs doc webpage

### ISSUE THREAD

**Issue by shadachi** [Quantomatic/pyzx#86]
Hello, I am a newcomer to ZX calculus and PyZX so please pardon my ignorance.

I am running the demo notebook gettingstarted.ipynb using the PyZX 0.7 release. The demo starts by generating a random Clifford circuit but with the seed set to 1337. I notice that this is the same circuit as the web page https://pyzx.readthedocs.io/en/latest/gettingstarted.html.

However when I run the notebook, the simplified ZX diagram after clifford_simp() and normalize() is slightly different (both diagrams have 8 Z-spiders, but the phases and edges don't quite match) and after extract_circuit() the circuits are vastly different. The result on the web page is much simpler, it has just 9 Z spiders, 9 X spiders, and 6 Hadamard edges, whereas the result in my notebook is a much longer circuit, 39 Z spiders, 6 X spiders, and 18 Hadamard edges.

Am I doing something wrong, or was the demo web page perhaps created using an earlier version of PyZX? (e.g. I notice there is a call to Circuit.to_graph(), which doesn't appear to be in the current API) It would certainly be nice to get that simpler result, if that is also correct ...

**Comment by jvdwetering** [comment]
You are not doing anything wrong. There must have been some changes to the rewriting strategy that cause this particular circuit to be brought to a different normal form that is less good. I don't know how you can get back the old one, sorry.
