### ISSUE TITLE
Add ry gate to qasm spec

### ISSUE THREAD

**Issue by jvdwetering** [Quantomatic/pyzx#90]
As noted in #44, the qasm parser currently doesn't understand the `ry` gate. By looking at the definition of this gate in the Qiskit source, it should be relatively straightforward to implement support for this gate.

**Comment by fuglede** [comment]
I wonder if this is working as intended after #101? It is indeed possible to use `zx.Circuit.from_qasm` with a QASM string that has `ry` gates in it to get a circuit `circ`, but it is not possible to, say, run `zx.basic_optimization` on the result even though it's possible to get something that works after running it through `zx.extract_circuit(circ.to_graph())`.

**Comment by jvdwetering** [comment]
This is not really well-documented, but `basic_optimization` requires the gates to be from a restricted set. Generally you want to call `to_basic_gates()` before calling `basic_optimization`.

**Comment by dlyongemallo** [comment]
This isn't quite working even after PR #101. The rotation implemented there is in the reverse direction to how the [`RYGate` is defined in qiskit](https://qiskit.org/documentation/stubs/qiskit.circuit.library.RYGate.html). In particular, this means that `compare_tensors` will always return `False` (even with `preserve_scalar` set to `False`) for any circuit imported into pyzx from a qasm file output by qiskit. 

Repro case:
```
from pyzx.circuit import Circuit
from pyzx.tensor import compare_tensors
from qiskit import quantum_info
from qiskit.circuit import QuantumCircuit

qasm = """
OPENQASM 2.0;
include "qelib1.inc";
qreg q[1];
ry(pi/2) q[0];
"""
c = Circuit.from_qasm(qasm)
t1 = c.to_matrix()
print(t1)

qc = QuantumCircuit.from_qasm_str(qasm)
t2 = quantum_info.Operator(qc).data
print(t2)

print(compare_tensors(t1, t2, False))
```

Output:
```
[[ 0.5+0.5j  0.5+0.5j]
 [-0.5-0.5j  0.5+0.5j]]
[[ 0.70710678+0.j -0.70710678+0.j]
 [ 0.70710678+0.j  0.70710678+0.j]]
False
```

**Comment by jvdwetering** [comment]
In the test of #101  they write
```
def test_ry_preserves_graph_semantics(self):
        g = self.c.to_graph()
        t = tensor_to_matrix(tensorfy(g, False), 1, 1)
        expected_t = np.asarray([[np.cos(np.pi/8), np.sin(np.pi/8)], [-np.sin(np.pi/8), np.cos(np.pi/8)]])
        self.assertTrue(compare_tensors(t, expected_t, False))
```
However, the Wikipedia page defines the Y rotation differently https://en.wikipedia.org/wiki/List_of_quantum_logic_gates#Rotation_operator_gates:
![image](https://github.com/Quantomatic/pyzx/assets/15610543/54cb96c7-a102-4a1b-9d8e-a2f6f2123213)
So it looks like the XPhase(alpha) should be replaced by a XPhase(-alpha) in #101
