### ISSUE TITLE
Unable reach the diagram of depth 6 for Cliffords

### ISSUE THREAD

**Issue by danielecuomo** [Quantomatic/pyzx#94]
As stated in _Graph-theoretic Simplification of Quantum Circuits with the ZX-calculus_, a Clifford circuit can always be transformed in a graph-like diagram corresponding with a sub-diagram occurring in the middle and performing parity-checks -- see equation (11) of the above paper.

However I can't reach this form but only a similar one. And I struggle to understand what are the steps to reach this form.

I posted such issue also at the link below.

https://quantumcomputing.stackexchange.com/questions/27162/pyzx-optimisation-steps-for-clifford-circuits?noredirect=1#comment35564_27162

**Comment by danielecuomo** [comment]
It is clear in theory, especially by reading the paper. However, when using the built-in methods, I am unable to obtain the CZ layers.

Below the steps I do:

`g = zx.generate.cliffordT(qubits, depth)
zx.simplify.interior_clifford_simp(g)
g.normalize()
zx.simplify.to_rg(g, select = lambda v: set(g.neighbors(v)).intersection(g.outputs()))

`

**Comment by jvdwetering** [comment]
Ah yeah, I don't think there currently is a built-in way to do that, apart from what is implemented in the `extract_circuit` method. It shouldn't be too hard to implement it yourself though: find all the spiders connected to an input, and then for every Hadamard connection between these spiders, unfuse a spider into a CZ (this is essentially what `extract_circuit` does, but then immediately unto a `Circuit`, while I think you are wanting to keep it in the form of a `Graph`?).

**Comment by danielecuomo** [comment]
Yes, I'd like to reach that `Graph` and then implement my own `extract_circuit` method.

**Comment by danielecuomo** [comment]
For example extracting a circuit from starting from the following generation:
`rnd.seed(2)
d = 16
q = 4
g = zx.generate.cliffordT(qubits = q, depth = d, p_s=0.2, p_hsh=0.2, p_cnot=0.6)`

**Comment by danielecuomo** [comment]
In alternative I tried to use the extract_simple method. But I get the error:
`Algorithm failed: Graph is not fully reduced`

**Comment by jvdwetering** [comment]
So the problem I think is that the `extract_circuit` method does it in such a way that it generates both CNOTs and CZs during extraction. You can probably get it back to the correct form by pushing some Hadamards through CZs to turn them into CNOTs. But this is all not implemented in a method. I might get around to implementing a method that given a Clifford normal form, spits out a circuit of the form described in the paper, but this is currently not high on my todo list.

Is there a specific project or thing you need it for?

**Comment by danielecuomo** [comment]
Soon, my paper on https://arxiv.org/abs/2112.14139 will be published on ACM Transaction on Quantum Computing.

I perform a distributed compilation over Clifford in normal forms. In such a paper I just give a numerical evaluation starting from random normal forms.

In order to use the library pyzx I need it to be able to give in output a Clifford circuit in normal form.

**Comment by danielecuomo** [comment]
The case in the picture doesn't look to me like something that I can bring back to the normal form.

<img width="780" alt="Screenshot 2022-11-17 at 11 01 19" src="https://user-images.githubusercontent.com/37900917/202429306-1b1af13f-1419-4352-a0be-1ff90aa6bec6.png">

**Comment by jvdwetering** [comment]
Yeah I don't exactly see how that corresponds to a normal form either, weird. Okay, I'll look into making a dedicated function for this, because it would be a nice thing to have.

**Comment by danielecuomo** [comment]
Great! Thanks a lot. Looking forward to use it!

**Comment by danielecuomo** [comment]
Greetings,
Is there any news? Thank you!

**Comment by jvdwetering** [comment]
Sorry, I got distracted with other things. The function I just added should do what you asked. Now that I am at it I also want to add a function that also immediately converts it to a `Circuit`.

**Comment by danielecuomo** [comment]
Great, thank you!

**Comment by jvdwetering** [comment]
And now also implemented a new function `zx.extract.extract_clifford_normal_form` that immediately gives you a circuit out.

**Comment by jvdwetering** [comment]
Can I close this issue?

**Comment by danielecuomo** [comment]
I already closed it.

Daniele
