### ISSUE TITLE
Modding phases by 2 in QASM's u2 and u3

### ISSUE THREAD

**Issue by 525125** [Quantomatic/pyzx#95]
Since `exp(-iZ * theta/2)` has period `4π`,  I'm wondering why some phases are modded by 2 rather than by 4, e.g. 
https://github.com/Quantomatic/pyzx/blob/e2d7aed7610943e1e17700c488c7eb197e7c1d5b/pyzx/circuit/qasmparser.py#L195
Doesn't this potentially introduce a phase of -1?

And why is only one argument in `u3` not modded by 2?
https://github.com/Quantomatic/pyzx/blob/e2d7aed7610943e1e17700c488c7eb197e7c1d5b/pyzx/circuit/qasmparser.py#L193

**Comment by jvdwetering** [comment]
Sorry for responding so late.

`Circuit`s in PyZX don't care about global phase, so the 4pi periodicity you are referring to wouldn't be visible at this level, as it is just a global phase difference. Additionally, `ZPhase(alpha) = diag(1,e^{i alpha})` is not  equal to `exp(-iZ * alpha/2) = diag(e^{-i alpha/2},e^{i alpha/2}`, as they differ by a global phase that makes `ZPhase` exactly 2pi periodic.

I don't remember why there is an inconsistency in which phases are modded by 2pi in the `qasmparser`, but for these reasons it doesn't make a difference to the circuit.
